version: '3'

services:
  todo-app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: todo-app
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    # build:
    #   context: app
    #   dockerfile: ./Dockerfile
    # environment:
    #   NODE_ENV: production
    ports:
      - 27017:27017
    volumes:
      - todo-app-data:/data/db

volumes:
  todo-app-data:
