version: '3'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    # env_file:
    #   - ./.env
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - wordpress-network
    depends_on:
      - wordpress-db

  wordpress-db:
    image: mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    # env_file:
    #   - ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - wordpress-db-data:/var/lib/mysql
    networks:
      - wordpress-network

volumes:
  wordpress-data:
  wordpress-db-data:

networks:
  wordpress-network:
    driver: bridge