version: '3'

services:
  vue-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    # environment:
    #   NODE_ENV: production
    container_name: vue-app
    ports:
      - 8080:8080
